name: Static_Analysis

on:
  push:
    branches: 
      - master
      - littlegnal/try-workflow-run
  pull_request:
    branches: 
      - master
      - littlegnal/try-workflow-run

jobs:
  unittest_flutter:
    name: Run Flutter Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.10.0'
      - run: flutter pub get
